reboot_wallbox:
  description: Reboot alfen wallbox
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "alfen_wallbox.garage"

set_current_limit:
  description: Set current charge limit
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "alfen_wallbox.garage"
    limit:
      description: New limit.