reboot_wallbox:
  description: Reboot alfen wallbox
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "alfen_wallbox.garage"

set_current_limit:
  description: Set current charge limit
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "alfen_wallbox.garage"
    limit:
      description: New limit.

enable_rfid_authorization_mode:
  description: Enables RFID auth mode
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "alfen_wallbox.garage"

disable_rfid_authorization_mode:
  description: Disables RFID auth mode
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "alfen_wallbox.garage"

set_current_phase:
  description: Set current phase mapping to L1
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "alfen_wallbox.garage"
    phase:
      description: phase.

enable_phase_switching:
  description: Enable phase switching
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "alfen_wallbox.garage"

disable_phase_switching:
  description: Disable phase switching
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "alfen_wallbox.garage"
